conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import permission_required, user_passes_test

from ikwen.accesscontrol.utils import is_staff
from ikwen.core.views import Offline

from ikwen_kakocase.shopping.views import FlatPageView, Home
from ikwen_kakocase.kakocase.views import Welcome, AdminHome, GuardPage, FirstTime
from ikwen_kakocase.trade.provider.views import ProviderDashboard, CCMDashboard

from website.views import PinsView, Kakocase, Webnode, Terms, About

# from playground.views import save_ghost_user
from playground.views import confirm_checkout, PlaygroundCart

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^kakocase/', Kakocase.as_view(), name='kakocase'),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),
    url(r'^pinsview$', PinsView.as_view(), name='pinsview'),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^terms$', Terms.as_view(), name='terms_and_conditions'),
    url(r'^about$', About.as_view(), name='about'),
    url(r'^shopping/cart/$', PlaygroundCart.as_view(), name='cart'),
    url(r'^shopping/cart/(?P<order_id>[-\w]+)/$', PlaygroundCart.as_view(), name='cart'),
    url(r'^shopping/', include('ikwen_kakocase.shopping.urls', namespace='shopping')),
    url(r'^playground/confirm_checkout', confirm_checkout, name='confirm_checkout'),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currencies/', include('currencies.urls')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),

    url(r'^ikwen/dashboard/$', permission_required('trade.ik_view_dashboard')(ProviderDashboard.as_view()), name='dashboard'),
    url(r'^ikwen/CCMDashboard/$', permission_required('trade.ik_view_dashboard')(CCMDashboard.as_view()), name='ccm_dashboard'),
    url(r'^ikwen/theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^cci/', include('ikwen_kakocase.cci.urls', namespace='cci')),
    url(r'^ikwen/cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^ikwen/home/$', user_passes_test(is_staff)(AdminHome.as_view()), name='admin_home'),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^echo/', include('echo.urls', namespace='echo')),

    # url(r'^$', ProviderDashboard.as_view(), name='admin_home'),
    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),

    url(r'^welcome/$', Welcome.as_view(), name='welcome'),
    url(r'^firstTime/$', FirstTime.as_view(), name='first_time'),
    url(r'^guardPage/$', GuardPage.as_view(), name='guard_page'),

    url(r'^home/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^$', Home.as_view(), name='home'),

    url(r'^offline.html$', Offline.as_view(), name='offline'),
    # url(r'^save_ghost_user$', save_ghost_user, name='save_ghost_user'),
)

templates/billing/momo_checkout.html
{% extends "core/base_bs.html" %}
{% load i18n staticfiles humanize %}

{% block page_title %}<title>{% trans "Mobile Money Checkout" %} - {{ service.project_name }} </title>{% endblock %}
{% block head_style %}
    {{ block.super }}
    <link rel='stylesheet' href="{% static 'ikwen/css/momo.css' %}" />
{% endblock %}

{% block content %}
    <div id="content" class="container">
        <div class="visible-xs" style="float: left; width: 100%; padding: 15px 0"></div>
        <div id="checkout">
            <div style="margin-bottom: 45px">
                <div class="pull-left" style="width: 50%">
                   {% if request.GET.method %}
                        <img src="{% static 'ikwen/img/logo-OM-200x166.png' %}" alt="orange-money" class="img-responsive" style="height: 45px" />
                    {% else %}
                        <img src="{{ settings.IKWEN_MEDIA_URL }}{{ payment_mean.logo.name }}" alt="{{ payment_mean.name }}" class="img-responsive" style="height: 45px" />
                    {% endif %}
                </div>
                <div class="pull-right">
                    {% if request.session.merchant_name %}
                        <h4 class="text-right visible-xs" style="margin-top: 0">{{ request.session.merchant_name|truncatechars:"18" }}</h4>
                        <h4 class="text-right hidden-xs" style="margin-top: 0">{{ request.session.merchant_name }}</h4>
                    {% endif %}
                    <div style="color: #03A9F4">
                        <i class="glyphicon glyphicon-shopping-cart" style="color: #3F51B5; font-size: 21px; margin-right: 5px"></i>
                        {{ config.currency_symbol }} <strong>{{ amount|floatformat:"0"|intcomma }}</strong>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <h3 style="text-align: center"> {% trans "Pay with" %}{% if request.GET.method %} Orange Money  {% else %} {{ payment_mean.name }} {% endif %}</h3>
            <p class="text-muted" style="text-align: center"> {% trans "Type your phone number and submit" %} </p>
            <p class="momo-warning">
                {% trans 'Your phone number must be registered to' %}
                {% if not request.GET.method %}
                    <a href="https://www.mtncameroon.net/en/mtn-mobile-money/" target="_blank">MTN Mobile Money</a> service
                {% else %}
                    <span style="color: #EF620E;">Orange Money</span> service
                {% endif %}
            </p>
            <form onsubmit="return false">{% csrf_token %}
                <div class="form-group" style="margin-top: .4em">
                    <label for="phone" class="sr-only">{% trans "Phone number" %}</label>
                    <input id="phone" class="form-control input-sm" type="text" name="phone" value="{{ phone }}" />
                </div>
                <div class="form-group">
                    <button id="do-pay" class="btn btn-primary btn-block btn-sm"> {% trans "Submit" %} </button>
                    {% include 'core/snippets/spinner.html' %}
                </div>
                <div id="transaction-result" class="text-info"></div>
            </form>
        </div>
        <div style="margin: 45px 15px">
            <a href="{% if request.session.cancel_url %}{{ request.session.cancel_url }}{% else %}{{ request.META.HTTP_REFERER }}{% endif %}"
               class="cancel-payment">{% trans "Cancel" %}</a>
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        (function() {
            $('#do-pay').click(function () {
                var phone = $('#phone').val();
                if (phone.length !== 9 && phone.length !== 12) {
                    alert('Invalid phone number');
                    return;
                }
                if (!$(this).hasClass('btn-primary')) return;
                $(this).removeClass('btn-primary').addClass('btn-default');
                $('#checkout .spinner').show();
                setTimeout(function () {
                    $.ajax({
                        url: "{% url 'confirm_checkout' %}",
                        data: {phone: phone},
                        error: function(req, status, error) {
                            $('#checkout .spinner').hide();
                            $('#transaction-result').removeClass('text-info').addClass('text-danger')
                                    .text(status + ": " + error);
                            $('#do-pay').removeClass('btn-default').addClass('btn-primary');
                        },
                        success: function(data) {
                            window.location = "{% url 'shopping:cart' request.session.object_id %}";
                        }
                    });
                }, 3000);
            });
        })()
    </script>
    {{ config.scripts|safe }}
{% endblock %}